sonar.projectKey=andreguima-github_mylife
sonar.organization=andreguima-github
sonar.projectName=mylife
sonar.sourceEncoding=UTF-8
sonar.tests=backend/tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info