import assert from "node:assert/strict";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

function request(service, method, input, verb, ...expectedArgs) {
  return {
    name: `${service.constructor.name || "service"}.${method}`,
    invoke: () => service[method](...input),
    verb,
    expectedArgs,
  };
}

test("service methods delegate to the expected API routes and payloads", async (t) => {
  const vite = await createServer({
    configFile: false,
    root: fileURLToPath(new URL("../../", import.meta.url)),
    optimizeDeps: { noDiscovery: true },
    server: { middlewareMode: true },
    appType: "custom",
  });
  t.after(() => vite.close());

  const serviceNames = [
    "authService",
    "bankAccountsService",
    "creditCardsService",
    "dreamsService",
    "expenseCategoriesService",
    "expensesService",
    "habitsService",
    "investmentIncomesService",
    "investmentsService",
    "notesService",
    "preferencesService",
    "quotesService",
    "readingListService",
    "reportsService",
    "usersService",
  ];
  const services = Object.fromEntries(
    await Promise.all(
      serviceNames.map(async (name) => [
        name,
        (await vite.ssrLoadModule(`/src/services/${name}.js`)).default,
      ]),
    ),
  );
  const api = (await vite.ssrLoadModule("/src/services/api.js")).default;
  const {
    authService,
    bankAccountsService,
    creditCardsService,
    dreamsService,
    expenseCategoriesService,
    expensesService,
    habitsService,
    investmentIncomesService,
    investmentsService,
    notesService,
    preferencesService,
    quotesService,
    readingListService,
    reportsService,
    usersService,
  } = services;

  for (const verb of ["get", "post", "patch", "put", "delete"]) {
    t.mock.method(api, verb, (...args) => ({ verb, args }));
  }

  const payload = { name: "sample" };
  const cases = [
    request(
      authService,
      "login",
      [{ email: "a@b.test", password: "secret" }],
      "post",
      "/auth/login",
      { email: "a@b.test", password: "secret" },
    ),
    request(
      authService,
      "register",
      [payload],
      "post",
      "/auth/register",
      payload,
    ),
    request(
      authService,
      "forgotPassword",
      ["a@b.test"],
      "post",
      "/auth/forgot-password",
      { email: "a@b.test" },
    ),
    request(
      authService,
      "validateResetToken",
      ["reset"],
      "get",
      "/auth/reset-password/validate",
      { params: { token: "reset" } },
    ),
    request(
      authService,
      "resetPassword",
      [{ token: "reset", new_password: "new" }],
      "post",
      "/auth/reset-password",
      { token: "reset", new_password: "new" },
    ),
    request(
      authService,
      "verifyEmail",
      ["verify"],
      "get",
      "/auth/verify-email",
      { params: { token: "verify" } },
    ),
    request(
      authService,
      "resendVerificationEmail",
      ["a@b.test"],
      "post",
      "/auth/resend-verification-email",
      { email: "a@b.test" },
    ),
    request(bankAccountsService, "list", [], "get", "/bank-accounts", {
      params: {},
    }),
    request(
      bankAccountsService,
      "list",
      [{ active: true }],
      "get",
      "/bank-accounts",
      { params: { active: true } },
    ),
    request(
      bankAccountsService,
      "snapshots",
      [],
      "get",
      "/bank-accounts/patrimony-snapshots",
      { params: { days: 365 } },
    ),
    request(
      bankAccountsService,
      "snapshots",
      [7],
      "get",
      "/bank-accounts/patrimony-snapshots",
      { params: { days: 7 } },
    ),
    request(
      bankAccountsService,
      "create",
      [payload],
      "post",
      "/bank-accounts",
      payload,
    ),
    request(
      bankAccountsService,
      "transfer",
      [payload],
      "post",
      "/bank-accounts/transfer",
      payload,
    ),
    request(
      bankAccountsService,
      "update",
      [3, payload],
      "patch",
      "/bank-accounts/3",
      payload,
    ),
    request(bankAccountsService, "remove", [3], "delete", "/bank-accounts/3"),
    request(creditCardsService, "list", [], "get", "/credit-cards"),
    request(
      creditCardsService,
      "create",
      [payload],
      "post",
      "/credit-cards",
      payload,
    ),
    request(
      creditCardsService,
      "update",
      [3, payload],
      "patch",
      "/credit-cards/3",
      payload,
    ),
    request(creditCardsService, "remove", [3], "delete", "/credit-cards/3"),
    request(dreamsService, "list", [], "get", "/dreams"),
    request(dreamsService, "getById", [3], "get", "/dreams/3"),
    request(dreamsService, "create", [payload], "post", "/dreams", payload),
    request(
      dreamsService,
      "update",
      [3, payload],
      "patch",
      "/dreams/3",
      payload,
    ),
    request(dreamsService, "remove", [3], "delete", "/dreams/3"),
    request(
      dreamsService,
      "toggleMilestone",
      [3, 4],
      "post",
      "/dreams/3/milestones/4/toggle",
    ),
    request(
      dreamsService,
      "updateMilestone",
      [3, 4, payload],
      "patch",
      "/dreams/3/milestones/4",
      payload,
    ),
    request(expenseCategoriesService, "list", [], "get", "/expense-categories"),
    request(
      expenseCategoriesService,
      "create",
      [payload],
      "post",
      "/expense-categories",
      payload,
    ),
    request(
      expenseCategoriesService,
      "update",
      [3, payload],
      "patch",
      "/expense-categories/3",
      payload,
    ),
    request(
      expenseCategoriesService,
      "remove",
      [3],
      "delete",
      "/expense-categories/3",
    ),
    request(expensesService, "list", [], "get", "/expenses"),
    request(
      expensesService,
      "list",
      [
        {
          fromDate: "2026-01-01",
          toDate: "2026-01-31",
          year: 2026,
          month: 1,
          categoryId: 4,
          limit: 10,
          offset: 20,
        },
      ],
      "get",
      "/expenses?from=2026-01-01&to=2026-01-31&year=2026&month=1&category_id=4&limit=10&offset=20",
    ),
    request(
      expensesService,
      "summary",
      [{ fromDate: "2026-01-01", year: 2026, limit: 10, offset: 20 }],
      "get",
      "/expenses/summary?from=2026-01-01&year=2026",
    ),
    request(expensesService, "create", [payload], "post", "/expenses", payload),
    request(
      expensesService,
      "update",
      [3, payload],
      "patch",
      "/expenses/3",
      payload,
    ),
    request(expensesService, "remove", [3], "delete", "/expenses/3"),
    request(
      expensesService,
      "payCreditInvoice",
      [payload],
      "post",
      "/expenses/pay-credit-invoice",
      payload,
    ),
    request(habitsService, "list", [], "get", "/habits", { params: {} }),
    request(habitsService, "create", [payload], "post", "/habits", payload),
    request(
      habitsService,
      "update",
      [3, payload],
      "patch",
      "/habits/3",
      payload,
    ),
    request(habitsService, "toggle", [3], "post", "/habits/3/toggle"),
    request(habitsService, "stats", [3], "get", "/habits/3/stats"),
    request(habitsService, "history", [3], "get", "/habits/3/history", {
      params: {},
    }),
    request(habitsService, "heatmap", [3], "get", "/habits/3/heatmap", {
      params: { days: 90 },
    }),
    request(habitsService, "heatmap", [3, 30], "get", "/habits/3/heatmap", {
      params: { days: 30 },
    }),
    request(investmentIncomesService, "list", [], "get", "/investment-incomes"),
    request(
      investmentIncomesService,
      "list",
      [{ fromDate: "2026-01-01", toDate: "2026-01-31" }],
      "get",
      "/investment-incomes?from=2026-01-01&to=2026-01-31",
    ),
    request(
      investmentIncomesService,
      "create",
      [payload],
      "post",
      "/investment-incomes",
      payload,
    ),
    request(
      investmentIncomesService,
      "update",
      [3, payload],
      "patch",
      "/investment-incomes/3",
      payload,
    ),
    request(
      investmentIncomesService,
      "remove",
      [3],
      "delete",
      "/investment-incomes/3",
    ),
    request(investmentsService, "list", [], "get", "/investments"),
    request(
      investmentsService,
      "create",
      [payload],
      "post",
      "/investments",
      payload,
    ),
    request(
      investmentsService,
      "update",
      [3, payload],
      "patch",
      "/investments/3",
      payload,
    ),
    request(investmentsService, "remove", [3], "delete", "/investments/3"),
    request(
      investmentsService,
      "syncPrices",
      [],
      "post",
      "/investments/sync-prices",
    ),
    request(
      investmentsService,
      "history",
      [3],
      "get",
      "/investments/3/price-history",
    ),
    request(
      investmentsService,
      "history",
      [3, { limit: 5 }],
      "get",
      "/investments/3/price-history?limit=5",
    ),
    request(notesService, "list", [], "get", "/notes"),
    request(notesService, "create", [payload], "post", "/notes", payload),
    request(notesService, "update", [3, payload], "patch", "/notes/3", payload),
    request(notesService, "remove", [3], "delete", "/notes/3"),
    request(
      preferencesService,
      "get",
      ["habits"],
      "get",
      "/preferences/habits",
    ),
    request(
      preferencesService,
      "update",
      ["habits", payload],
      "put",
      "/preferences/habits",
      { preferences: payload },
    ),
    request(quotesService, "list", [], "get", "/quotes"),
    request(quotesService, "getById", [3], "get", "/quotes/3"),
    request(quotesService, "create", [payload], "post", "/quotes", payload),
    request(quotesService, "update", [3, payload], "put", "/quotes/3", payload),
    request(quotesService, "remove", [3], "delete", "/quotes/3"),
    request(quotesService, "getQuoteOfTheDay", [], "get", "/quotes/of-the-day"),
    request(readingListService, "list", [], "get", "/reading-list", {
      params: undefined,
    }),
    request(readingListService, "list", ["reading"], "get", "/reading-list", {
      params: { status: "reading" },
    }),
    request(readingListService, "get", [3], "get", "/reading-list/3"),
    request(
      readingListService,
      "create",
      [payload],
      "post",
      "/reading-list",
      payload,
    ),
    request(
      readingListService,
      "update",
      [3, payload],
      "patch",
      "/reading-list/3",
      payload,
    ),
    request(readingListService, "remove", [3], "delete", "/reading-list/3"),
    request(
      readingListService,
      "listLogs",
      [3],
      "get",
      "/reading-list/3/logs",
      { params: { limit: 30 } },
    ),
    request(
      readingListService,
      "upsertLog",
      [3, payload],
      "post",
      "/reading-list/3/logs",
      payload,
    ),
    request(
      reportsService,
      "dailyCashflow",
      [],
      "get",
      "/reports/daily-cashflow",
    ),
    request(
      reportsService,
      "dailyCashflow",
      [{ from: "2026-01-01", to: "2026-01-31" }],
      "get",
      "/reports/daily-cashflow?from=2026-01-01&to=2026-01-31",
    ),
    request(usersService, "getAll", [], "get", "/admin/users/"),
    request(
      usersService,
      "update",
      [3, payload],
      "put",
      "/admin/users/3",
      payload,
    ),
    request(usersService, "remove", [3], "delete", "/admin/users/3"),
    request(usersService, "restore", [3], "post", "/admin/users/3/restore"),
  ];

  for (const { name, invoke, verb, expectedArgs } of cases) {
    assert.deepEqual(await invoke(), { verb, args: expectedArgs }, name);
  }
});
